version: "3.3"

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://si5_sacc:dev_password@database:5432/td_1
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc
      - POSTGRES_DB=td_1