version: "3.3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRESQL_ADDON_DB=td_1
      - POSTGRESQL_ADDON_HOST=database
      - POSTGRESQL_ADDON_PASSWORD=dev_password
      - POSTGRESQL_ADDON_USER=si5_sacc
      - POSTGRESQL_ADDON_PORT=5432
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc
      - POSTGRES_DB=td_1